# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from basedpyright 1.39.9 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from typing import Any, TypeVar

from footman.tools import Argv as _Argv
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

_R = TypeVar("_R")

class Basedpyright(_Tool[_R]):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        baselinefile: _Value = ...,
        createstub: _Value = ...,
        dependencies: _Flag = ...,
        gitlabcodequality: _Value = ...,
        ignoreexternal: _Flag = ...,
        level: _Value = ...,
        outputjson: _Flag = ...,
        project: _Value = ...,
        pythonpath: _Value = ...,
        pythonplatform: _Value = ...,
        pythonversion: _Value = ...,
        skipunannotated: _Flag = ...,
        stats: _Flag = ...,
        threads: _Value = ...,
        typeshedpath: _Value = ...,
        venvpath: _Value = ...,
        verbose: _Flag = ...,
        verifytypes: _Value = ...,
        warnings: _Flag = ...,
        watch: _Flag = ...,
        writebaseline: _Flag = ...,
        **flags: Any,
    ) -> _R:
        """Run this verb.

        Args:
            baselinefile: Path to the baseline file to be used.
            createstub: Create type stub file(s) for import.
            dependencies: Emit import dependency information.
            gitlabcodequality: Output results to a gitlab code quality report.
            ignoreexternal: Ignore external imports for --verifytypes.
            level: Minimum diagnostic level (error or warning).
            outputjson: Output results in JSON format.
            project: Use the configuration file at this location.
            pythonpath: Path to the Python interpreter.
            pythonplatform: Analyze for a specific platform (Darwin, Linux, Windows,
                iOS, Android).
            pythonversion: Analyze for a specific version (3.3, 3.4, etc.).
            skipunannotated: Skip analysis of functions with no type annotations.
            stats: Print detailed performance stats.
            threads: Use separate threads to parallelize type checking.
            typeshedpath: Use typeshed type stubs at this location.
            venvpath: Directory that contains virtual environments.
            verbose: Emit verbose diagnostics.
            verifytypes: Verify type completeness of a py.typed package.
            warnings: Use exit code of 1 if warnings are reported.
            watch: Continue to run and watch for changes.
            writebaseline: Write new errors to the baseline file.
        """
        ...
    @property
    def argv(self) -> Basedpyright[_Argv]: ...
