# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from pyproject-build 1.5.1 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from typing import Any, TypeVar

from footman.tools import Argv as _Argv
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

_R = TypeVar("_R")

class Build(_Tool[_R]):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        config_json: _Value = ...,
        config_setting: _Value = ...,
        dependency_constraints_txt: _Value = ...,
        env_dir: _Value = ...,
        installer: _Value = ...,
        metadata: _Flag = ...,
        no_isolation: _Flag = ...,
        outdir: _Value = ...,
        quiet: _Flag = ...,
        report: _Value = ...,
        sdist: _Flag = ...,
        sdist_extract_dir: _Value = ...,
        skip_dependency_check: _Flag = ...,
        verbose: _Flag = ...,
        wheel: _Flag = ...,
        **flags: Any,
    ) -> _R:
        """A simple, correct Python build frontend.

        Args:
            config_json: settings to pass to the backend as a JSON object. Added in
                1.3.0.
            config_setting: settings to pass to the backend.
            dependency_constraints_txt: constrain build dependencies using a
                constraints.txt when installing dependencies. Added in 1.4.1.
            env_dir: create the isolated build environment at this location instead
                of a temporary directory. Added in 1.5.1.
            installer: Python package installer to use (defaults to pip).
            metadata: print out a wheel's metadata in JSON format, building it first
                unless the source argument is already a .whl. Added in 1.4.0.
            no_isolation: disable building the project in an isolated virtual
                environment.
            outdir: output directory (defaults to {srcdir}\\dist).
            quiet: reduce verbosity. Added in 1.4.0.
            report: write a machine-readable JSON report of the built artifacts
                (name, path, kind, size and SHA-256 hash) to this path. Added in
                1.5.1.
            sdist: build a source distribution (disables the default behavior).
            sdist_extract_dir: extract the intermediate sdist to PATH (created if
                missing and kept afterwards) instead of a random temporary
                directory; reusing it across rebuilds gives compiler caches such as
                ccache/sccache a stable source path. Added in 1.5.1.
            skip_dependency_check: do not check that build dependencies are
                installed.
            verbose: increase verbosity.
            wheel: build a wheel (disables the default behavior).
        """
        ...
    @property
    def argv(self) -> Build[_Argv]: ...
