# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from bun 1.3.14 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from typing import Any, Self, TypeVar

from footman.tools import Argv as _Argv
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

_R = TypeVar("_R")
_R2 = TypeVar("_R2")

class Bun(_Tool[_R]):
    class Add(_Tool[_R2]):
        def __call__(  # type: ignore[override]
            self,
            *args: str,
            analyze: _Flag = ...,
            backend: _Value = ...,
            ca: _Value = ...,
            cache_dir: _Value = ...,
            cafile: _Value = ...,
            concurrent_scripts: _Value = ...,
            config: _Value = ...,
            cpu: _Value = ...,
            cwd: _Value = ...,
            dev: _Flag = ...,
            dry_run: _Flag = ...,
            exact: _Flag = ...,
            force: _Flag = ...,
            frozen_lockfile: _Flag = ...,
            global_: _Flag = ...,
            ignore_scripts: _Flag = ...,
            linker: _Value = ...,
            lockfile_only: _Flag = ...,
            minimum_release_age: _Value = ...,
            network_concurrency: _Value = ...,
            no_cache: _Flag = ...,
            no_progress: _Flag = ...,
            no_summary: _Flag = ...,
            no_verify: _Flag = ...,
            omit: _Value = ...,
            only_missing: _Flag = ...,
            optional: _Flag = ...,
            os: _Value = ...,
            peer: _Flag = ...,
            production: _Flag = ...,
            quiet: _Flag = ...,
            registry: _Value = ...,
            save: _Flag = ...,
            save_text_lockfile: _Flag = ...,
            silent: _Flag = ...,
            trust: _Flag = ...,
            verbose: _Flag = ...,
            yarn: _Flag = ...,
            **flags: Any,
        ) -> _R2:
            """Alias: bun a

            Args:
                analyze: Recursively analyze & install dependencies of files passed
                    as arguments (using Bun's bundler).
                backend: Platform-specific optimizations for installing
                    dependencies.
                ca: Provide a Certificate Authority signing certificate.
                cache_dir: Store & load cached data from a specific directory path.
                cafile: The same as `--ca`, but is a file path to the certificate.
                concurrent_scripts: Maximum number of concurrent jobs for lifecycle
                    scripts. Defaults to `2x CPU cores`.
                config: Specify path to config file (bunfig.toml).
                cpu: Override CPU architecture for optional dependencies (e.g., x64,
                    arm64, * for all).
                cwd: Set a specific cwd.
                dev: Add dependency to "devDependencies".
                dry_run: Perform a dry run without making changes.
                exact: Add the exact version instead of the ^range.
                force: Always request the latest versions from the registry &
                    reinstall all dependencies.
                frozen_lockfile: Disallow changes to lockfile.
                global_: Install globally.
                ignore_scripts: Skip lifecycle scripts in the project's package.json
                    (dependency scripts are never run).
                linker: Linker strategy (one of "isolated" or "hoisted").
                lockfile_only: Generate a lockfile without installing dependencies.
                minimum_release_age: Only install packages published at least N
                    seconds ago (security feature).
                network_concurrency: Maximum number of concurrent network requests.
                    Defaults to `48`.
                no_cache: Ignore manifest cache entirely.
                no_progress: Disable the progress bar.
                no_summary: Don't print a summary.
                no_verify: Skip verifying integrity of newly downloaded packages.
                omit: Exclude 'dev', 'optional', or 'peer' dependencies from
                    install.
                only_missing: Only add dependencies to package.json if they are not
                    already present.
                optional: Add dependency to "optionalDependencies".
                os: Override operating system for optional dependencies (e.g.,
                    linux, darwin, * for all).
                peer: Add dependency to "peerDependencies".
                production: Don't install devDependencies.
                quiet: Only show tarball name when packing.
                registry: Use a specific registry by default, overriding .npmrc,
                    bunfig.toml and environment variables.
                save: Save to package.json (true by default). `save=off` emits
                    `--no-save`.
                save_text_lockfile: Save a text-based lockfile.
                silent: Don't log anything.
                trust: Add to trustedDependencies in the project's package.json and
                    install the package(s).
                verbose: Excessively verbose logging.
                yarn: Write a yarn.lock file (yarn v1).
            """
            ...
        @property
        def argv(self) -> Bun.Add[_Argv]: ...

    add: Add[_R]
    class Build(_Tool[_R2]):
        def __call__(  # type: ignore[override]
            self,
            entrypoint: str,
            /,
            *args: str,
            allow_unresolved: _Value = ...,
            app: _Flag = ...,
            asset_naming: _Value = ...,
            banner: _Value = ...,
            bytecode: _Flag = ...,
            chunk_naming: _Value = ...,
            compile: _Flag = ...,
            compile_autoload_bunfig: _Flag = ...,
            compile_autoload_dotenv: _Flag = ...,
            compile_autoload_package_json: _Flag = ...,
            compile_autoload_tsconfig: _Flag = ...,
            compile_exec_argv: _Value = ...,
            compile_executable_path: _Value = ...,
            conditions: _Value = ...,
            css_chunking: _Flag = ...,
            emit_dce_annotations: _Flag = ...,
            entry_naming: _Value = ...,
            env: _Value = ...,
            external: _Value = ...,
            footer: _Value = ...,
            format: _Value = ...,
            keep_names: _Flag = ...,
            metafile: _Value = ...,
            metafile_md: _Value = ...,
            minify: _Flag = ...,
            minify_identifiers: _Flag = ...,
            minify_syntax: _Flag = ...,
            minify_whitespace: _Flag = ...,
            no_bundle: _Flag = ...,
            no_clear_screen: _Flag = ...,
            outdir: _Value = ...,
            outfile: _Value = ...,
            packages: _Value = ...,
            production: _Flag = ...,
            public_path: _Value = ...,
            react_fast_refresh: _Flag = ...,
            reject_unresolved: _Flag = ...,
            root: _Value = ...,
            server_components: _Flag = ...,
            sourcemap: _Value = ...,
            splitting: _Flag = ...,
            target: _Value = ...,
            watch: _Flag = ...,
            windows_copyright: _Value = ...,
            windows_description: _Value = ...,
            windows_hide_console: _Flag = ...,
            windows_icon: _Value = ...,
            windows_publisher: _Value = ...,
            windows_title: _Value = ...,
            windows_version: _Value = ...,
            **flags: Any,
        ) -> _R2:
            """Run this verb.

            Args:
                allow_unresolved: Allow unresolved dynamic import()/require()
                    specifiers matching these glob patterns. Added in 1.3.11.
                app: (EXPERIMENTAL) Build a web app for production using Bun Bake.
                asset_naming: Customize asset filenames.
                banner: Add a banner to the bundled output such as "use client"; for
                    a bundle being used with RSCs.
                bytecode: Use a bytecode cache.
                chunk_naming: Customize chunk filenames.
                compile: Generate a standalone Bun executable containing your
                    bundled code.
                compile_autoload_bunfig: Enable autoloading of bunfig.toml in
                    standalone executable. Defaults on —
                    `compile_autoload_bunfig=off` emits
                    `--no-compile-autoload-bunfig`.
                compile_autoload_dotenv: Enable autoloading of .env files in
                    standalone executable. Defaults on —
                    `compile_autoload_dotenv=off` emits
                    `--no-compile-autoload-dotenv`.
                compile_autoload_package_json: Enable autoloading of package.json at
                    runtime in standalone executable.
                    `compile_autoload_package_json=off` emits
                    `--no-compile-autoload-package-json`.
                compile_autoload_tsconfig: Enable autoloading of tsconfig.json at
                    runtime in standalone executable.
                    `compile_autoload_tsconfig=off` emits
                    `--no-compile-autoload-tsconfig`.
                compile_exec_argv: Prepend arguments to the standalone executable's
                    execArgv.
                compile_executable_path: Path to a Bun executable to use for
                    cross-compilation instead of downloading. Added in 1.3.6.
                conditions: Pass custom conditions to resolve.
                css_chunking: Chunk CSS files together to reduce duplicated CSS
                    loaded in a browser.
                emit_dce_annotations: Re-emit DCE annotations in bundles.
                entry_naming: Customize entry point filenames.
                env: Inline environment variables into the bundle as
                    process.env.${name}.
                external: Exclude module from transpilation (can use * wildcards).
                footer: Add a footer to the bundled output such as // built with
                    bun!.
                format: Specifies the module format to build to.
                keep_names: Preserve original function and class names when
                    minifying.
                metafile: Write a JSON file with metadata about the build. Added in
                    1.3.6.
                metafile_md: Write a markdown file with a visualization of the
                    module graph (LLM-friendly). Added in 1.3.8.
                minify: Enable all minification flags.
                minify_identifiers: Minify identifiers.
                minify_syntax: Minify syntax and inline data.
                minify_whitespace: Minify whitespace.
                no_bundle: Transpile file only, do not bundle.
                no_clear_screen: Disable clearing the terminal screen on reload when
                    --watch is enabled.
                outdir: Default to "dist" if multiple files.
                outfile: Write to a file.
                packages: Add dependencies to bundle or keep them external.
                production: Set NODE_ENV=production and enable minification.
                public_path: A prefix to be appended to any import paths in bundled
                    code.
                react_fast_refresh: Enable React Fast Refresh transform (does not
                    emit hot-module code, use this for testing).
                reject_unresolved: Fail the build on any dynamic import()/require()
                    specifier that cannot be resolved at build time. Added in
                    1.3.11.
                root: Root directory used for multiple entry points.
                server_components: (EXPERIMENTAL) Enable server components.
                sourcemap: Build with sourcemaps - 'linked', 'inline', 'external',
                    or 'none'.
                splitting: Enable code splitting.
                target: The intended execution environment for the bundle.
                watch: Automatically restart the process on file change.
                windows_copyright: When using --compile targeting Windows, set the
                    executable copyright.
                windows_description: When using --compile targeting Windows, set the
                    executable description.
                windows_hide_console: When using --compile targeting Windows,
                    prevent a Command prompt from opening alongside the executable.
                windows_icon: When using --compile targeting Windows, assign an
                    executable icon.
                windows_publisher: When using --compile targeting Windows, set the
                    executable company name.
                windows_title: When using --compile targeting Windows, set the
                    executable product name.
                windows_version: When using --compile targeting Windows, set the
                    executable version (e.g.
            """
            ...
        @property
        def argv(self) -> Bun.Build[_Argv]: ...

    build: Build[_R]
    class Install(_Tool[_R2]):
        def __call__(  # type: ignore[override]
            self,
            *args: str,
            analyze: _Flag = ...,
            backend: _Value = ...,
            ca: _Value = ...,
            cache_dir: _Value = ...,
            cafile: _Value = ...,
            concurrent_scripts: _Value = ...,
            config: _Value = ...,
            cpu: _Value = ...,
            cwd: _Value = ...,
            dev: _Flag = ...,
            dry_run: _Flag = ...,
            exact: _Flag = ...,
            filter: _Value = ...,
            force: _Flag = ...,
            frozen_lockfile: _Flag = ...,
            global_: _Flag = ...,
            ignore_scripts: _Flag = ...,
            linker: _Value = ...,
            lockfile_only: _Flag = ...,
            minimum_release_age: _Value = ...,
            network_concurrency: _Value = ...,
            no_cache: _Flag = ...,
            no_progress: _Flag = ...,
            no_summary: _Flag = ...,
            no_verify: _Flag = ...,
            omit: _Value = ...,
            only_missing: _Flag = ...,
            optional: _Flag = ...,
            os: _Value = ...,
            peer: _Flag = ...,
            production: _Flag = ...,
            quiet: _Flag = ...,
            registry: _Value = ...,
            save: _Flag = ...,
            save_text_lockfile: _Flag = ...,
            silent: _Flag = ...,
            trust: _Flag = ...,
            verbose: _Flag = ...,
            yarn: _Flag = ...,
            **flags: Any,
        ) -> _R2:
            """Alias: bun i

            Args:
                analyze: Analyze & install all dependencies of files passed as
                    arguments recursively (using Bun's bundler).
                backend: Platform-specific optimizations for installing
                    dependencies.
                ca: Provide a Certificate Authority signing certificate.
                cache_dir: Store & load cached data from a specific directory path.
                cafile: The same as `--ca`, but is a file path to the certificate.
                concurrent_scripts: Maximum number of concurrent jobs for lifecycle
                    scripts. Defaults to `2x CPU cores`.
                config: Specify path to config file (bunfig.toml).
                cpu: Override CPU architecture for optional dependencies (e.g., x64,
                    arm64, * for all).
                cwd: Set a specific cwd.
                dev: Add dependency to "devDependencies".
                dry_run: Perform a dry run without making changes.
                exact: Add the exact version instead of the ^range.
                filter: Install packages for the matching workspaces.
                force: Always request the latest versions from the registry &
                    reinstall all dependencies.
                frozen_lockfile: Disallow changes to lockfile.
                global_: Install globally.
                ignore_scripts: Skip lifecycle scripts in the project's package.json
                    (dependency scripts are never run).
                linker: Linker strategy (one of "isolated" or "hoisted").
                lockfile_only: Generate a lockfile without installing dependencies.
                minimum_release_age: Only install packages published at least N
                    seconds ago (security feature).
                network_concurrency: Maximum number of concurrent network requests.
                    Defaults to `48`.
                no_cache: Ignore manifest cache entirely.
                no_progress: Disable the progress bar.
                no_summary: Don't print a summary.
                no_verify: Skip verifying integrity of newly downloaded packages.
                omit: Exclude 'dev', 'optional', or 'peer' dependencies from
                    install.
                only_missing: Only add dependencies to package.json if they are not
                    already present.
                optional: Add dependency to "optionalDependencies".
                os: Override operating system for optional dependencies (e.g.,
                    linux, darwin, * for all).
                peer: Add dependency to "peerDependencies".
                production: Don't install devDependencies.
                quiet: Only show tarball name when packing.
                registry: Use a specific registry by default, overriding .npmrc,
                    bunfig.toml and environment variables.
                save: Save to package.json (true by default). `save=off` emits
                    `--no-save`.
                save_text_lockfile: Save a text-based lockfile.
                silent: Don't log anything.
                trust: Add to trustedDependencies in the project's package.json and
                    install the package(s).
                verbose: Excessively verbose logging.
                yarn: Write a yarn.lock file (yarn v1).
            """
            ...
        @property
        def argv(self) -> Bun.Install[_Argv]: ...

    install: Install[_R]
    class Remove(_Tool[_R2]):
        def __call__(  # type: ignore[override]
            self,
            *args: str,
            backend: _Value = ...,
            ca: _Value = ...,
            cache_dir: _Value = ...,
            cafile: _Value = ...,
            concurrent_scripts: _Value = ...,
            config: _Value = ...,
            cpu: _Value = ...,
            cwd: _Value = ...,
            dry_run: _Flag = ...,
            force: _Flag = ...,
            frozen_lockfile: _Flag = ...,
            global_: _Flag = ...,
            ignore_scripts: _Flag = ...,
            linker: _Value = ...,
            lockfile_only: _Flag = ...,
            minimum_release_age: _Value = ...,
            network_concurrency: _Value = ...,
            no_cache: _Flag = ...,
            no_progress: _Flag = ...,
            no_summary: _Flag = ...,
            no_verify: _Flag = ...,
            omit: _Value = ...,
            os: _Value = ...,
            production: _Flag = ...,
            quiet: _Flag = ...,
            registry: _Value = ...,
            save: _Flag = ...,
            save_text_lockfile: _Flag = ...,
            silent: _Flag = ...,
            trust: _Flag = ...,
            verbose: _Flag = ...,
            yarn: _Flag = ...,
            **flags: Any,
        ) -> _R2:
            """Alias: bun r

            Args:
                backend: Platform-specific optimizations for installing
                    dependencies.
                ca: Provide a Certificate Authority signing certificate.
                cache_dir: Store & load cached data from a specific directory path.
                cafile: The same as `--ca`, but is a file path to the certificate.
                concurrent_scripts: Maximum number of concurrent jobs for lifecycle
                    scripts. Defaults to `2x CPU cores`.
                config: Specify path to config file (bunfig.toml).
                cpu: Override CPU architecture for optional dependencies (e.g., x64,
                    arm64, * for all).
                cwd: Set a specific cwd.
                dry_run: Perform a dry run without making changes.
                force: Always request the latest versions from the registry &
                    reinstall all dependencies.
                frozen_lockfile: Disallow changes to lockfile.
                global_: Install globally.
                ignore_scripts: Skip lifecycle scripts in the project's package.json
                    (dependency scripts are never run).
                linker: Linker strategy (one of "isolated" or "hoisted").
                lockfile_only: Generate a lockfile without installing dependencies.
                minimum_release_age: Only install packages published at least N
                    seconds ago (security feature).
                network_concurrency: Maximum number of concurrent network requests.
                    Defaults to `48`.
                no_cache: Ignore manifest cache entirely.
                no_progress: Disable the progress bar.
                no_summary: Don't print a summary.
                no_verify: Skip verifying integrity of newly downloaded packages.
                omit: Exclude 'dev', 'optional', or 'peer' dependencies from
                    install.
                os: Override operating system for optional dependencies (e.g.,
                    linux, darwin, * for all).
                production: Don't install devDependencies.
                quiet: Only show tarball name when packing.
                registry: Use a specific registry by default, overriding .npmrc,
                    bunfig.toml and environment variables.
                save: Save to package.json (true by default). `save=off` emits
                    `--no-save`.
                save_text_lockfile: Save a text-based lockfile.
                silent: Don't log anything.
                trust: Add to trustedDependencies in the project's package.json and
                    install the package(s).
                verbose: Excessively verbose logging.
                yarn: Write a yarn.lock file (yarn v1).
            """
            ...
        @property
        def argv(self) -> Bun.Remove[_Argv]: ...

    remove: Remove[_R]
    class Run(_Tool[_R2]):
        def __call__(  # type: ignore[override]
            self,
            file: str,
            /,
            *args: str,
            bun: _Flag = ...,
            conditions: _Value = ...,
            config: _Value = ...,
            console_depth: _Value = ...,
            cpu_prof: _Flag = ...,
            cpu_prof_dir: _Value = ...,
            cpu_prof_interval: _Value = ...,
            cpu_prof_md: _Flag = ...,
            cpu_prof_name: _Value = ...,
            cron_period: _Value = ...,
            cron_title: _Value = ...,
            cwd: _Value = ...,
            define: _Value = ...,
            dns_result_order: _Value = ...,
            drop: _Value = ...,
            elide_lines: _Value = ...,
            env_file: _Value = ...,
            eval: _Value = ...,
            experimental_http2_fetch: _Flag = ...,
            experimental_http3_fetch: _Flag = ...,
            expose_gc: _Flag = ...,
            extension_order: _Value = ...,
            feature: _Value = ...,
            fetch_preconnect: _Value = ...,
            filter: _Value = ...,
            heap_prof: _Flag = ...,
            heap_prof_dir: _Value = ...,
            heap_prof_md: _Flag = ...,
            heap_prof_name: _Value = ...,
            hot: _Flag = ...,
            i: _Flag = ...,
            if_present: _Flag = ...,
            ignore_dce_annotations: _Flag = ...,
            import_: _Value = ...,
            inspect: _Value = ...,
            inspect_brk: _Value = ...,
            inspect_wait: _Value = ...,
            install: _Value = ...,
            jsx_factory: _Value = ...,
            jsx_fragment: _Value = ...,
            jsx_import_source: _Value = ...,
            jsx_runtime: _Value = ...,
            jsx_side_effects: _Flag = ...,
            loader: _Value = ...,
            main_fields: _Value = ...,
            max_http_header_size: _Value = ...,
            no_addons: _Flag = ...,
            no_clear_screen: _Flag = ...,
            no_deprecation: _Flag = ...,
            no_env_file: _Flag = ...,
            no_exit_on_error: _Flag = ...,
            no_install: _Flag = ...,
            no_macros: _Flag = ...,
            no_orphans: _Flag = ...,
            parallel: _Flag = ...,
            port: _Value = ...,
            prefer_latest: _Flag = ...,
            prefer_offline: _Flag = ...,
            preload: _Value = ...,
            preserve_symlinks: _Flag = ...,
            preserve_symlinks_main: _Flag = ...,
            print: _Value = ...,
            redis_preconnect: _Flag = ...,
            require: _Value = ...,
            sequential: _Flag = ...,
            shell: _Value = ...,
            silent: _Flag = ...,
            smol: _Flag = ...,
            sql_preconnect: _Flag = ...,
            throw_deprecation: _Flag = ...,
            title: _Value = ...,
            tsconfig_override: _Value = ...,
            unhandled_rejections: _Value = ...,
            use_bundled_ca: _Flag = ...,
            use_openssl_ca: _Flag = ...,
            use_system_ca: _Flag = ...,
            user_agent: _Value = ...,
            watch: _Flag = ...,
            workspaces: _Flag = ...,
            zero_fill_buffers: _Flag = ...,
            **flags: Any,
        ) -> _R2:
            """Run this verb.

            Args:
                bun: Force a script or package to use Bun's runtime instead of
                    Node.js (via symlinking node).
                conditions: Pass custom conditions to resolve.
                config: Specify path to Bun config file.
                console_depth: Set the default depth for console.log object
                    inspection. Defaults to `2`.
                cpu_prof: Start CPU profiler and write profile to disk on exit.
                cpu_prof_dir: Specify the directory where the CPU profile will be
                    saved.
                cpu_prof_interval: Specify the sampling interval in microseconds for
                    CPU profiling. Defaults to `1000`. Added in 1.3.9.
                cpu_prof_md: Output CPU profile in markdown format (grep-friendly,
                    designed for LLM analysis). Added in 1.3.7.
                cpu_prof_name: Specify the name of the CPU profile file.
                cron_period: Cron period for cron execution mode. Added in 1.3.11.
                cron_title: Title for cron execution mode. Added in 1.3.11.
                cwd: Absolute path to resolve files & entry points from.
                define: Substitute K:V while parsing, e.g. --define
                    process.env.NODE_ENV:"development".
                dns_result_order: Set the default order of DNS lookup results.
                drop: Remove function calls, e.g. --drop=console removes all
                    console.* calls.
                elide_lines: Number of lines of script output shown when using
                    --filter . Defaults to `10`.
                env_file: Load environment variables from the specified file(s).
                eval: Evaluate argument as a script.
                experimental_http2_fetch: Offer h2 in fetch() TLS ALPN. Added in
                    1.3.14.
                experimental_http3_fetch: Honor Alt-Svc: h3 in fetch() and upgrade
                    to HTTP/3. Added in 1.3.14.
                expose_gc: Expose gc() on the global object.
                extension_order: Defaults to: .tsx,.ts,.jsx,.js,.json.
                feature: Enable a feature flag for dead-code elimination, e.g.
                    --feature=SUPER_SECRET.
                fetch_preconnect: Preconnect to a URL while code is loading.
                filter: Run a script in all workspace packages matching the pattern.
                heap_prof: Generate V8 heap snapshot on exit (.heapsnapshot). Added
                    in 1.3.7.
                heap_prof_dir: Specify the directory where the heap profile will be
                    saved. Added in 1.3.7.
                heap_prof_md: Generate markdown heap profile on exit (for CLI
                    analysis). Added in 1.3.7.
                heap_prof_name: Specify the name of the heap profile file. Added in
                    1.3.7.
                hot: Enable auto reload in the Bun runtime, test runner, or bundler.
                i: Auto-install dependencies during execution.
                if_present: Exit without an error if the entrypoint does not exist.
                ignore_dce_annotations: Ignore tree-shaking annotations such as
                    @__PURE__.
                import_: Alias of --preload, for Node.js compatibility.
                inspect: Activate Bun's debugger.
                inspect_brk: Activate Bun's debugger, set breakpoint on first line
                    of code and wait.
                inspect_wait: Activate Bun's debugger, wait for a connection before
                    executing.
                install: Configure auto-install behavior.
                jsx_factory: Changes the function called when compiling JSX elements
                    using the classic JSX runtime.
                jsx_fragment: Changes the function called when compiling JSX
                    fragments.
                jsx_import_source: Declares the module specifier to be used for
                    importing the jsx and jsxs factory functions.
                jsx_runtime: "automatic" (default) or "classic".
                jsx_side_effects: Treat JSX elements as having side effects (disable
                    pure annotations).
                loader: Parse files with .ext:loader, e.g. --loader .js:jsx.
                main_fields: Main fields to lookup in package.json.
                max_http_header_size: Set the maximum size of HTTP headers in bytes.
                no_addons: Throw an error if process.dlopen is called, and disable
                    export condition "node-addons".
                no_clear_screen: Disable clearing the terminal screen on reload when
                    --hot or --watch is enabled.
                no_deprecation: Suppress all reporting of the custom deprecation.
                no_env_file: Disable automatic loading of .env files.
                no_exit_on_error: Continue running other scripts when one fails
                    (with --parallel/--sequential). Added in 1.3.9.
                no_install: Disable auto install in the Bun runtime.
                no_macros: Disable macros from being executed in the bundler,
                    transpiler and runtime.
                no_orphans: Exit when the parent process dies, and on exit SIGKILL
                    every descendant. Added in 1.3.14.
                parallel: Run multiple scripts concurrently with Foreman-style
                    output. Added in 1.3.9.
                port: Set the default port for Bun.serve.
                prefer_latest: Use the latest matching versions of packages in the
                    Bun runtime, always checking npm.
                prefer_offline: Skip staleness checks for packages in the Bun
                    runtime and resolve from disk.
                preload: Import a module before other modules are loaded.
                preserve_symlinks: Preserve symlinks when resolving files.
                preserve_symlinks_main: Preserve symlinks when resolving the main
                    entry point.
                print: Evaluate argument as a script and print the result.
                redis_preconnect: Preconnect to $REDIS_URL at startup.
                require: Alias of --preload, for Node.js compatibility.
                sequential: Run multiple scripts sequentially with Foreman-style
                    output. Added in 1.3.9.
                shell: Control the shell used for package.json scripts.
                silent: Don't print the script command.
                smol: Use less memory, but run garbage collection more often.
                sql_preconnect: Preconnect to PostgreSQL at startup.
                throw_deprecation: Determine whether or not deprecation warnings
                    result in errors.
                title: Set the process title.
                tsconfig_override: Specify custom tsconfig.json.
                unhandled_rejections: One of "strict", "throw", "warn", "none", or
                    "warn-with-error-code".
                use_bundled_ca: Use bundled CA store.
                use_openssl_ca: Use OpenSSL's default CA store.
                use_system_ca: Use the system's trusted certificate authorities.
                user_agent: Set the default User-Agent header for HTTP requests.
                watch: Automatically restart the process on file change.
                workspaces: Run a script in all workspace packages (from the
                    "workspaces" field in package.json).
                zero_fill_buffers: Boolean to force Buffer.allocUnsafe(size) to be
                    zero-filled.
            """
            ...
        @property
        def argv(self) -> Bun.Run[_Argv]: ...

    run: Run[_R]
    class Test(_Tool[_R2]):
        def __call__(  # type: ignore[override]
            self,
            *args: str,
            bail: _Value = ...,
            changed: _Value = ...,
            concurrent: _Flag = ...,
            coverage: _Flag = ...,
            coverage_dir: _Value = ...,
            coverage_reporter: _Value = ...,
            dots: _Flag = ...,
            isolate: _Flag = ...,
            max_concurrency: _Value = ...,
            no_orphans: _Flag = ...,
            only: _Flag = ...,
            only_failures: _Flag = ...,
            parallel: _Value = ...,
            parallel_delay: _Value = ...,
            pass_with_no_tests: _Flag = ...,
            path_ignore_patterns: _Value = ...,
            randomize: _Flag = ...,
            reporter: _Value = ...,
            reporter_outfile: _Value = ...,
            rerun_each: _Value = ...,
            retry: _Value = ...,
            seed: _Value = ...,
            shard: _Value = ...,
            test_name_pattern: _Value = ...,
            test_worker: _Flag = ...,
            timeout: _Value = ...,
            todo: _Flag = ...,
            update_snapshots: _Flag = ...,
            **flags: Any,
        ) -> _R2:
            """Run this verb.

            Args:
                bail: Exit the test suite after <NUMBER> failures.
                changed: Only run test files affected by changed files according to
                    git. Added in 1.3.13.
                concurrent: Treat all tests as `test.concurrent()` tests.
                coverage: Generate a coverage profile.
                coverage_dir: Directory for coverage files.
                coverage_reporter: Report coverage in 'text' and/or 'lcov'.
                dots: Enable dots reporter.
                isolate: Run each test file in a fresh global object. Added in
                    1.3.13.
                max_concurrency: Maximum number of concurrent tests to execute at
                    once.
                no_orphans: Exit when the parent process dies, and on exit SIGKILL
                    every descendant. Added in 1.3.14.
                only: Run only tests that are marked with "test.only()" or
                    "describe.only()".
                only_failures: Only display test failures, hiding passing tests.
                parallel: Run test files in parallel using N worker processes. Added
                    in 1.3.13.
                parallel_delay: Milliseconds the first --parallel worker must be
                    busy before spawning the rest. Added in 1.3.13.
                pass_with_no_tests: Exit with code 0 when no tests are found.
                path_ignore_patterns: Glob patterns for test file paths to ignore.
                    Added in 1.3.11.
                randomize: Run tests in random order.
                reporter: Test output reporter format.
                reporter_outfile: Output file path for the reporter format (required
                    with --reporter).
                rerun_each: Re-run each test file <NUMBER> times, helps catch
                    certain bugs.
                retry: Default retry count for all tests, overridden by per-test {
                    retry: N }. Added in 1.3.10.
                seed: Set the random seed for test randomization.
                shard: Run a subset of test files, e.g. '--shard=1/3' runs the first
                    of three shards. Added in 1.3.13.
                test_name_pattern: Run only tests with a name that matches the given
                    regex.
                test_worker: (internal) Run as a --parallel worker, receiving files
                    over IPC. Added in 1.3.13.
                timeout: Set the per-test timeout in milliseconds, default is 5000.
                todo: Include tests that are marked with "test.todo()".
                update_snapshots: Update snapshot files.
            """
            ...
        @property
        def argv(self) -> Bun.Test[_Argv]: ...

    test: Test[_R]
    class X(_Tool[_R2]):
        def __call__(  # type: ignore[override]
            self,
            *args: str,
            bun: _Flag = ...,
            no_install: _Flag = ...,
            package: _Value = ...,
            silent: _Flag = ...,
            verbose: _Flag = ...,
            **flags: Any,
        ) -> _R2:
            """Execute an npm package executable (CLI), automatically installing into a
            global shared cache if not installed in node_modules.

            Args:
                bun: Force the command to run with Bun instead of Node.js.
                no_install: Skip installation if package is not already installed.
                package: Specify package to install when binary name differs from
                    package name.
                silent: Suppress output during installation.
                verbose: Enable verbose output during installation.
            """
            ...
        @property
        def argv(self) -> Bun.X[_Argv]: ...

    x: X[_R]
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        bun: _Flag = ...,
        conditions: _Value = ...,
        config: _Value = ...,
        console_depth: _Value = ...,
        cpu_prof: _Flag = ...,
        cpu_prof_dir: _Value = ...,
        cpu_prof_interval: _Value = ...,
        cpu_prof_md: _Flag = ...,
        cpu_prof_name: _Value = ...,
        cron_period: _Value = ...,
        cron_title: _Value = ...,
        cwd: _Value = ...,
        dns_result_order: _Value = ...,
        elide_lines: _Value = ...,
        env_file: _Value = ...,
        eval: _Value = ...,
        experimental_http2_fetch: _Flag = ...,
        experimental_http3_fetch: _Flag = ...,
        expose_gc: _Flag = ...,
        fetch_preconnect: _Value = ...,
        filter: _Value = ...,
        heap_prof: _Flag = ...,
        heap_prof_dir: _Value = ...,
        heap_prof_md: _Flag = ...,
        heap_prof_name: _Value = ...,
        hot: _Flag = ...,
        i: _Flag = ...,
        if_present: _Flag = ...,
        import_: _Value = ...,
        inspect: _Value = ...,
        inspect_brk: _Value = ...,
        inspect_wait: _Value = ...,
        install: _Value = ...,
        max_http_header_size: _Value = ...,
        no_addons: _Flag = ...,
        no_clear_screen: _Flag = ...,
        no_deprecation: _Flag = ...,
        no_env_file: _Flag = ...,
        no_exit_on_error: _Flag = ...,
        no_install: _Flag = ...,
        no_orphans: _Flag = ...,
        parallel: _Flag = ...,
        port: _Value = ...,
        prefer_latest: _Flag = ...,
        prefer_offline: _Flag = ...,
        preload: _Value = ...,
        print: _Value = ...,
        redis_preconnect: _Flag = ...,
        require: _Value = ...,
        revision: _Flag = ...,
        sequential: _Flag = ...,
        shell: _Value = ...,
        silent: _Flag = ...,
        smol: _Flag = ...,
        sql_preconnect: _Flag = ...,
        throw_deprecation: _Flag = ...,
        title: _Value = ...,
        unhandled_rejections: _Value = ...,
        use_bundled_ca: _Flag = ...,
        use_openssl_ca: _Flag = ...,
        use_system_ca: _Flag = ...,
        user_agent: _Value = ...,
        watch: _Flag = ...,
        workspaces: _Flag = ...,
        zero_fill_buffers: _Flag = ...,
        **flags: Any,
    ) -> _R:
        """Bun is a fast JavaScript runtime, package manager, bundler, and test runner.
        (1.3.14+0d9b296af)

        Args:
            bun: Force a script or package to use Bun's runtime instead of Node.js
                (via symlinking node).
            conditions: Pass custom conditions to resolve.
            config: Specify path to Bun config file.
            console_depth: Set the default depth for console.log object inspection.
                Defaults to `2`.
            cpu_prof: Start CPU profiler and write profile to disk on exit.
            cpu_prof_dir: Specify the directory where the CPU profile will be saved.
            cpu_prof_interval: Specify the sampling interval in microseconds for CPU
                profiling. Defaults to `1000`. Added in 1.3.9.
            cpu_prof_md: Output CPU profile in markdown format (grep-friendly,
                designed for LLM analysis). Added in 1.3.7.
            cpu_prof_name: Specify the name of the CPU profile file.
            cron_period: Cron period for cron execution mode. Added in 1.3.11.
            cron_title: Title for cron execution mode. Added in 1.3.11.
            cwd: Absolute path to resolve files & entry points from.
            dns_result_order: Set the default order of DNS lookup results.
            elide_lines: Number of lines of script output shown when using --filter
                . Defaults to `10`.
            env_file: Load environment variables from the specified file(s).
            eval: Evaluate argument as a script.
            experimental_http2_fetch: Offer h2 in fetch() TLS ALPN. Added in 1.3.14.
            experimental_http3_fetch: Honor Alt-Svc: h3 in fetch() and upgrade to
                HTTP/3. Added in 1.3.14.
            expose_gc: Expose gc() on the global object.
            fetch_preconnect: Preconnect to a URL while code is loading.
            filter: Run a script in all workspace packages matching the pattern.
            heap_prof: Generate V8 heap snapshot on exit (.heapsnapshot). Added in
                1.3.7.
            heap_prof_dir: Specify the directory where the heap profile will be
                saved. Added in 1.3.7.
            heap_prof_md: Generate markdown heap profile on exit (for CLI analysis).
                Added in 1.3.7.
            heap_prof_name: Specify the name of the heap profile file. Added in
                1.3.7.
            hot: Enable auto reload in the Bun runtime, test runner, or bundler.
            i: Auto-install dependencies during execution.
            if_present: Exit without an error if the entrypoint does not exist.
            import_: Alias of --preload, for Node.js compatibility.
            inspect: Activate Bun's debugger.
            inspect_brk: Activate Bun's debugger, set breakpoint on first line of
                code and wait.
            inspect_wait: Activate Bun's debugger, wait for a connection before
                executing.
            install: Configure auto-install behavior.
            max_http_header_size: Set the maximum size of HTTP headers in bytes.
            no_addons: Throw an error if process.dlopen is called, and disable
                export condition "node-addons".
            no_clear_screen: Disable clearing the terminal screen on reload when
                --hot or --watch is enabled.
            no_deprecation: Suppress all reporting of the custom deprecation.
            no_env_file: Disable automatic loading of .env files.
            no_exit_on_error: Continue running other scripts when one fails (with
                --parallel/--sequential). Added in 1.3.9.
            no_install: Disable auto install in the Bun runtime.
            no_orphans: Exit when the parent process dies, and on exit SIGKILL every
                descendant. Added in 1.3.14.
            parallel: Run multiple scripts concurrently with Foreman-style output.
                Added in 1.3.9.
            port: Set the default port for Bun.serve.
            prefer_latest: Use the latest matching versions of packages in the Bun
                runtime, always checking npm.
            prefer_offline: Skip staleness checks for packages in the Bun runtime
                and resolve from disk.
            preload: Import a module before other modules are loaded.
            print: Evaluate argument as a script and print the result.
            redis_preconnect: Preconnect to $REDIS_URL at startup.
            require: Alias of --preload, for Node.js compatibility.
            revision: Print version with revision and exit.
            sequential: Run multiple scripts sequentially with Foreman-style output.
                Added in 1.3.9.
            shell: Control the shell used for package.json scripts.
            silent: Don't print the script command.
            smol: Use less memory, but run garbage collection more often.
            sql_preconnect: Preconnect to PostgreSQL at startup.
            throw_deprecation: Determine whether or not deprecation warnings result
                in errors.
            title: Set the process title.
            unhandled_rejections: One of "strict", "throw", "warn", "none", or
                "warn-with-error-code".
            use_bundled_ca: Use bundled CA store.
            use_openssl_ca: Use OpenSSL's default CA store.
            use_system_ca: Use the system's trusted certificate authorities.
            user_agent: Set the default User-Agent header for HTTP requests.
            watch: Automatically restart the process on file change.
            workspaces: Run a script in all workspace packages (from the
                "workspaces" field in package.json).
            zero_fill_buffers: Boolean to force Buffer.allocUnsafe(size) to be
                zero-filled.
        """
        ...
    @property
    def argv(self) -> Bun[_Argv]: ...
    def flags(
        self,
        *,
        bun: _Flag = ...,
        conditions: _Value = ...,
        config: _Value = ...,
        console_depth: _Value = ...,
        cpu_prof: _Flag = ...,
        cpu_prof_dir: _Value = ...,
        cpu_prof_interval: _Value = ...,
        cpu_prof_md: _Flag = ...,
        cpu_prof_name: _Value = ...,
        cron_period: _Value = ...,
        cron_title: _Value = ...,
        cwd: _Value = ...,
        dns_result_order: _Value = ...,
        elide_lines: _Value = ...,
        env_file: _Value = ...,
        eval: _Value = ...,
        experimental_http2_fetch: _Flag = ...,
        experimental_http3_fetch: _Flag = ...,
        expose_gc: _Flag = ...,
        fetch_preconnect: _Value = ...,
        filter: _Value = ...,
        heap_prof: _Flag = ...,
        heap_prof_dir: _Value = ...,
        heap_prof_md: _Flag = ...,
        heap_prof_name: _Value = ...,
        hot: _Flag = ...,
        i: _Flag = ...,
        if_present: _Flag = ...,
        import_: _Value = ...,
        inspect: _Value = ...,
        inspect_brk: _Value = ...,
        inspect_wait: _Value = ...,
        install: _Value = ...,
        max_http_header_size: _Value = ...,
        no_addons: _Flag = ...,
        no_clear_screen: _Flag = ...,
        no_deprecation: _Flag = ...,
        no_env_file: _Flag = ...,
        no_exit_on_error: _Flag = ...,
        no_install: _Flag = ...,
        no_orphans: _Flag = ...,
        parallel: _Flag = ...,
        port: _Value = ...,
        prefer_latest: _Flag = ...,
        prefer_offline: _Flag = ...,
        preload: _Value = ...,
        print: _Value = ...,
        redis_preconnect: _Flag = ...,
        require: _Value = ...,
        revision: _Flag = ...,
        sequential: _Flag = ...,
        shell: _Value = ...,
        silent: _Flag = ...,
        smol: _Flag = ...,
        sql_preconnect: _Flag = ...,
        throw_deprecation: _Flag = ...,
        title: _Value = ...,
        unhandled_rejections: _Value = ...,
        use_bundled_ca: _Flag = ...,
        use_openssl_ca: _Flag = ...,
        use_system_ca: _Flag = ...,
        user_agent: _Value = ...,
        watch: _Flag = ...,
        workspaces: _Flag = ...,
        zero_fill_buffers: _Flag = ...,
        **flags: Any,
    ) -> Self:
        """Bind tool-level global options before the subcommand.

        `tools.docker.flags(host=...)` puts a tool's own
        options ahead of the verb, where they belong."""
        ...
