# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from djlint 1.44.2 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from os import PathLike
from typing import Any, TypeVar

from toolroom import Argv, Flag, Value
from toolroom import Tool as ToolBase

_R = TypeVar("_R")

class Djlint(ToolBase[_R]):
    def __call__(  # type: ignore[override]
        self,
        src: str | PathLike[str],
        /,
        *args: str | PathLike[str],
        allow_empty_input: Flag = ...,
        blank_line_after_tag: Value = ...,
        blank_line_before_tag: Value = ...,
        check: Flag = ...,
        close_void_tags: Flag = ...,
        configuration: Value = ...,
        custom_blocks: Value = ...,
        custom_html: Value = ...,
        exclude: Value = ...,
        extend_exclude: Value = ...,
        extension: Value = ...,
        format_attribute_js_json: Flag = ...,
        format_attribute_js_json_min_props: Value = ...,
        format_attribute_js_json_pattern: Value = ...,
        format_attribute_template_tags: Flag = ...,
        format_css: Flag = ...,
        format_js: Flag = ...,
        github_output: Flag = ...,
        ignore: Value = ...,
        ignore_blocks: Value = ...,
        ignore_case: Flag = ...,
        include: Value = ...,
        indent: Value = ...,
        indent_css: Value = ...,
        indent_js: Value = ...,
        line_break_after_multiline_tag: Flag = ...,
        lint: Flag = ...,
        linter_output_format: Value = ...,
        max_attribute_length: Value = ...,
        max_blank_lines: Value = ...,
        max_line_length: Value = ...,
        no_function_formatting: Flag = ...,
        no_line_after_yaml: Flag = ...,
        no_set_formatting: Flag = ...,
        per_file_ignores: Value = ...,
        preserve_blank_lines: Flag = ...,
        preserve_class_newlines: Flag = ...,
        preserve_leading_space: Flag = ...,
        profile: Value = ...,
        quiet: Flag = ...,
        reformat: Flag = ...,
        require_pragma: Flag = ...,
        rules: Value = ...,
        single_attribute_per_line: Flag = ...,
        statistics: Flag = ...,
        stdin_filename: Value = ...,
        use_gitignore: Flag = ...,
        warn: Flag = ...,
        **flags: Any,
    ) -> _R:
        """djLint · HTML template linter and formatter.

        Args:
            allow_empty_input: Exit with 0 instead of 2 when the given paths match no files. Added in 1.44.0.
            blank_line_after_tag: Add an additional blank line after {% <tag> .
            blank_line_before_tag: Add an additional blank line before {% <tag> .
            check: Check formatting on the file(s).
            close_void_tags: Add closing mark on known void tags.
            configuration: Path to global configuration file in djlint.toml, .djlint.toml, or .djlintrc format.
            custom_blocks: Indent custom template blocks.
            custom_html: Indent custom HTML tags.
            exclude: Override the default exclude paths.
            extend_exclude: Add additional paths to the default exclude.
            extension: File extension to check. Defaults to `html`.
            format_attribute_js_json: Also format JavaScript/JSON inside HTML attributes.
            format_attribute_js_json_min_props: Minimum number of properties to treat attribute content as JS/JSON.
            format_attribute_js_json_pattern: Regex pattern to match JavaScript attributes.
            format_attribute_template_tags: Attempt to format template syntax inside of tag attributes.
            format_css: Also format contents of <style> tags.
            format_js: Also format contents of <script> tags.
            github_output: Output GitHub-compatible formatting.
            ignore: Codes to ignore.
            ignore_blocks: Comma list of template blocks to not indent.
            ignore_case: Do not fix case on known html tags.
            include: Codes to include.
            indent: Indent spacing. Defaults to `4`.
            indent_css: Set CSS indent level.
            indent_js: Set JS indent level.
            line_break_after_multiline_tag: Do not condense the content of multi-line tags into the line of the last attribute.
            lint: Lint for common issues.
            linter_output_format: Customize order of linter output message.
            max_attribute_length: Max attribute length. Defaults to `70`.
            max_blank_lines: Consolidate blank lines down to x lines. Defaults to `0`.
            max_line_length: Max line length. Defaults to `120`.
            no_function_formatting: Do not attempt to format function contents.
            no_line_after_yaml: Do not add a blank line after yaml front matter.
            no_set_formatting: Do not attempt to format set contents.
            per_file_ignores: Ignore linter rules on a per-file basis. May be repeated: a list emits the flag once per item.
            preserve_blank_lines: Attempt to preserve blank lines.
            preserve_class_newlines: Preserve line breaks inside multiline class attributes.
            preserve_leading_space: Attempt to preserve leading space on text.
            profile: Enable defaults by template language. Defaults to `html`.
            quiet: Do not print diff when reformatting.
            reformat: Reformat the file(s).
            require_pragma: Only format or lint files that starts with a comment with the text 'djlint:on'.
            rules: Path to custom rules file in .djlint_rules.yaml format. Added in 1.41.0.
            single_attribute_per_line: When an opening tag wraps, put each attribute on its own line.
            statistics: Count the number of occurrences of each error/warning code.
            stdin_filename: Filename to use for per-file-ignores and messages when reading from stdin. Defaults to `-`. Added in 1.43.0.
            use_gitignore: Use .gitignore file to extend excludes.
            warn: Return errors as warnings.
        """
        ...
    @property
    def argv(self) -> Djlint[Argv]: ...
