# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from git-cliff 2.13.1 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from collections.abc import Sequence
from os import PathLike
from typing import Any, Literal, TypeAlias, TypeVar

from toolroom import Argv, Flag, Value
from toolroom import Tool as ToolBase

_R = TypeVar("_R")

Sort: TypeAlias = Literal["oldest", "newest"]
Strip: TypeAlias = Literal["header", "footer", "all"]

class GitCliff(ToolBase[_R]):
    def __call__(  # type: ignore[override]
        self,
        *args: str | PathLike[str],
        azure_devops_repo: Value = ...,
        azure_devops_token: Value = ...,
        bitbucket_repo: Value = ...,
        bitbucket_token: Value = ...,
        body: Value = ...,
        bump: Value = ...,
        bumped_version: Flag = ...,
        config: Value = ...,
        config_url: Value = ...,
        context: Flag = ...,
        count_tags: Value = ...,
        current: Flag = ...,
        exclude_path: Value = ...,
        from_context: Value = ...,
        gitea_repo: Value = ...,
        gitea_token: Value = ...,
        github_repo: Value = ...,
        github_token: Value = ...,
        gitlab_repo: Value = ...,
        gitlab_token: Value = ...,
        ignore_tags: Value = ...,
        include_path: Value = ...,
        init: Value = ...,
        latest: Flag = ...,
        no_exec: Flag = ...,
        offline: Flag = ...,
        output: Value = ...,
        prepend: Value = ...,
        repository: Value = ...,
        skip_commit: Value = ...,
        skip_tags: Value = ...,
        sort: Sort | Sequence[Sort] | None = ...,
        strip: Strip | Sequence[Strip] | None = ...,
        tag: Value = ...,
        tag_pattern: Value = ...,
        topo_order: Flag = ...,
        unreleased: Flag = ...,
        use_branch_tags: Flag = ...,
        use_native_tls: Flag = ...,
        verbose: Flag = ...,
        with_commit: Value = ...,
        with_tag_message: Value = ...,
        workdir: Value = ...,
        **flags: Any,
    ) -> _R:
        """A highly customizable changelog generator ⛰️

        Args:
            azure_devops_repo: Sets the Azure DevOps repository. Added in 2.11.0.
            azure_devops_token: Sets the Azure DevOps API token. Added in 2.11.0.
            bitbucket_repo: Sets the Bitbucket repository.
            bitbucket_token: Sets the Bitbucket API token.
            body: Sets the template for the changelog body.
            bump: Bumps the version for unreleased changes.
            bumped_version: Prints bumped version for unreleased changes.
            config: Sets the configuration file. Defaults to `cliff.toml`.
            config_url: Sets the URL for the configuration file. Added in 2.9.1.
            context: Prints changelog context as JSON.
            count_tags: Sets the tags to count in the changelog.
            current: Processes the commits that belong to the current tag.
            exclude_path: Sets the path to exclude related commits. May be repeated: a list emits the flag once per item.
            from_context: Generates changelog from a JSON context.
            gitea_repo: Sets the Gitea repository.
            gitea_token: Sets the Gitea API token.
            github_repo: Sets the GitHub repository.
            github_token: Sets the GitHub API token.
            gitlab_repo: Sets the GitLab repository.
            gitlab_token: Sets the GitLab API token.
            ignore_tags: Sets the tags to ignore in the changelog.
            include_path: Sets the path to include related commits. May be repeated: a list emits the flag once per item.
            init: Writes the default configuration file to cliff.toml.
            latest: Processes the commits starting from the latest tag.
            no_exec: Disables the external command execution.
            offline: Disable network access for remote repositories. Added in 2.12.0.
            output: Writes output to the given file.
            prepend: Prepends entries to the given changelog file.
            repository: Sets the git repository. May be repeated: a list emits the flag once per item.
            skip_commit: Sets commits that will be skipped in the changelog. May be repeated: a list emits the flag once per item.
            skip_tags: Sets the tags to skip in the changelog. Added in 2.12.0.
            sort: Sets sorting of the commits inside sections. Defaults to `oldest`.
            strip: Strips the given parts from the changelog.
            tag: Sets the tag for the latest version.
            tag_pattern: Sets the regex for matching git tags.
            topo_order: Sorts the tags topologically.
            unreleased: Processes the commits that do not belong to a tag.
            use_branch_tags: Include only the tags that belong to the current branch.
            use_native_tls: Load TLS certificates from the native certificate store. Added in 2.8.0.
            verbose: Increases the logging verbosity.
            with_commit: Sets custom commit messages to include in the changelog. May be repeated: a list emits the flag once per item.
            with_tag_message: Sets custom message for the latest release.
            workdir: Sets the working directory.
        """
        ...
    @property
    def argv(self) -> GitCliff[Argv]: ...
