# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from git-changelog 2.9.6 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from os import PathLike
from typing import Any, TypeVar

from toolroom import Argv, Flag, Value
from toolroom import Tool as ToolBase

_R = TypeVar("_R")

class GitChangelog(ToolBase[_R]):
    def __call__(  # type: ignore[override]
        self,
        *args: str | PathLike[str],
        bump: Value = ...,
        bump_latest: Flag = ...,
        bumped_version: Flag = ...,
        config_file: Value = ...,
        convention: Value = ...,
        debug_info: Flag = ...,
        filter_commits: Value = ...,
        in_place: Flag = ...,
        include_all: Flag = ...,
        input: Value = ...,
        jinja_context: Value = ...,
        marker_line: Value = ...,
        no_zerover: Flag = ...,
        omit_empty_versions: Flag = ...,
        output: Value = ...,
        parse_refs: Flag = ...,
        provider: Value = ...,
        release_notes: Flag = ...,
        sections: Value = ...,
        template: Value = ...,
        trailers: Flag = ...,
        version_regex: Value = ...,
        versioning: Value = ...,
        **flags: Any,
    ) -> _R:
        """Automatic Changelog generator using Jinja2 templates.

        Args:
            bump: Specify the bump from latest version for the set of unreleased commits.
            bump_latest: Deprecated, use --bump=auto instead.
            bumped_version: Show bumped version and exit.
            config_file: Configuration file(s). May be repeated: a list emits the flag once per item.
            convention: The commit convention to match against.
            debug_info: Print debug information.
            filter_commits: The Git revision-range filter to use (e.g.
            in_place: Insert new entries (versions missing from changelog) in-place.
            include_all: Include all commits, even those without a recognized type.
            input: Read from given file when creating release notes.
            jinja_context: Pass additional key/value pairs to the template. May be repeated: a list emits the flag once per item.
            marker_line: A marker line at which to insert new entries (versions missing from changelog).
            no_zerover: By default, breaking changes on a 0.x don't bump the major version, maintaining it at 0.
            omit_empty_versions: Omit empty versions from the output.
            output: Output to given file.
            parse_refs: Parse provider-specific references in commit messages (GitHub/GitLab/Bitbucket issues, PRs, etc.).
            provider: Explicitly specify the repository provider.
            release_notes: Output release notes to stdout based on the last entry in the changelog.
            sections: A comma-separated list of sections to render.
            template: The Jinja2 template to use.
            trailers: Parse Git trailers in the commit message.
            version_regex: A regular expression to match versions in the existing changelog (used to find the latest release) when writing in-place.
            versioning: Versioning scheme to use when bumping and comparing versions.
        """
        ...
    @property
    def argv(self) -> GitChangelog[Argv]: ...
