# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from ninja 1.13.0 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from typing import Any, TypeVar

from footman.tools import Argv as _Argv
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

_R = TypeVar("_R")

class Ninja(_Tool[_R]):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        C: _Value = ...,
        d: _Value = ...,
        f: _Value = ...,
        j: _Value = ...,
        k: _Value = ...,
        l: _Value = ...,
        n: _Flag = ...,
        quiet: _Flag = ...,
        t: _Value = ...,
        verbose: _Flag = ...,
        w: _Value = ...,
        **flags: Any,
    ) -> _R:
        """if targets are unspecified, builds the 'default' target (see manual).

        Args:
            C: change to DIR before doing anything else.
            d: enable debugging (use '-d list' to list modes).
            f: specify input build file [default=build.ninja].
            j: run N jobs in parallel (0 means infinity) [default=30 on this
                system].
            k: keep going until N jobs fail (0 means infinity) [default=1].
            l: do not start new jobs if the load average is greater than N.
            n: dry run (don't run commands but act like they succeeded).
            quiet: don't show progress status, just command output. Added in 1.11.1.
            t: run a subtool (use '-t list' to list subtools) terminates toplevel
                options; further flags are passed to the tool.
            verbose: show all command lines while building.
            w: adjust warnings (use '-w list' to list warnings).
        """
        ...
    @property
    def argv(self) -> Ninja[_Argv]: ...
