# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from python 3.14.6 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from typing import Any, TypeVar

from footman.tools import Argv as _Argv
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

_R = TypeVar("_R")

class Python(_Tool[_R]):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        B: _Flag = ...,
        E: _Flag = ...,
        I: _Flag = ...,
        O: _Flag = ...,
        OO: _Flag = ...,
        P: _Flag = ...,
        S: _Flag = ...,
        V: _Flag = ...,
        W: _Value = ...,
        X: _Value = ...,
        b: _Flag = ...,
        c: _Value = ...,
        check_hash_based_pycs: _Value = ...,
        d: _Flag = ...,
        h: _Flag = ...,
        help_all: _Flag = ...,
        help_env: _Flag = ...,
        help_xoptions: _Value = ...,
        i: _Flag = ...,
        m: _Value = ...,
        q: _Flag = ...,
        s: _Flag = ...,
        u: _Flag = ...,
        v: _Flag = ...,
        x: _Flag = ...,
        **flags: Any,
    ) -> _R:
        """Run this verb.

        Args:
            B: don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x.
            E: ignore PYTHON* environment variables (such as PYTHONPATH).
            I: isolate Python from the user's environment (implies -E, -P and -s).
            O: remove assert and __debug__-dependent statements; add .opt-1 before
                .pyc extension; also PYTHONOPTIMIZE=x.
            OO: do -O changes and also discard docstrings; add .opt-2 before .pyc
                extension.
            P: don't prepend a potentially unsafe path to sys.path; also
                PYTHONSAFEPATH.
            S: don't imply 'import site' on initialization.
            V: print the Python version number and exit (also --version) when given
                twice, print more information about the build.
            W: warning control; arg is action:message:category:module:lineno also
                PYTHONWARNINGS=arg.
            X: set implementation-specific option.
            b: issue warnings about converting bytes/bytearray to str and comparing
                bytes/bytearray with str or bytes with int.
            c: program passed in as string (terminates option list).
            check_hash_based_pycs: control how Python invalidates hash-based .pyc
                files.
            d: turn on parser debugging output (for experts only, only works on
                debug builds); also PYTHONDEBUG=x.
            h: print this help message and exit (also -? or --help).
            i: inspect interactively after running script; forces a prompt even if
                stdin does not appear to be a terminal; also PYTHONINSPECT=x.
            m: run library module as a script (terminates option list).
            q: don't print version and copyright messages on interactive startup.
            s: don't add user site directory to sys.path; also PYTHONNOUSERSITE=x.
            u: force the stdout and stderr streams to be unbuffered; this option has
                no effect on stdin; also PYTHONUNBUFFERED=x.
            v: verbose (trace import statements); also PYTHONVERBOSE=x can be
                supplied multiple times to increase verbosity.
            x: skip first line of source, allowing use of non-Unix forms of #!cmd.
        """
        ...
    @property
    def argv(self) -> Python[_Argv]: ...
