# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from ty 0.0.73 on Linux, Windows and macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
from collections.abc import Sequence
from os import PathLike
from typing import Any, Literal, Self, TypeAlias, TypeVar

from toolroom import Argv, Flag, Value
from toolroom import Tool as ToolBase

_R = TypeVar("_R")
_R2 = TypeVar("_R2")

Color: TypeAlias = Literal["auto", "always", "never"]
OutputFormat: TypeAlias = Literal["full", "concise", "gitlab", "github", "junit"]
PythonVersion: TypeAlias = Literal[
    "3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "3.15"
]

class Ty(ToolBase[_R]):
    class Check(ToolBase[_R2]):
        def __call__(  # type: ignore[override]
            self,
            *args: str | PathLike[str],
            add_ignore: Flag = ...,
            color: Color | Sequence[Color] | None = ...,
            config: Value = ...,
            config_file: Value = ...,
            error: Value = ...,
            error_on_warning: Flag = ...,
            exclude: Value = ...,
            exclude_scripts: Flag = ...,
            exit_zero: Flag = ...,
            exit_zero_on_warning: Flag = ...,
            extra_search_path: Value = ...,
            fix: Flag = ...,
            force_exclude: Flag = ...,
            ignore: Value = ...,
            no_progress: Flag = ...,
            output_format: OutputFormat | Sequence[OutputFormat] | None = ...,
            project: Value = ...,
            python: Value = ...,
            python_platform: Value = ...,
            python_version: PythonVersion | Sequence[PythonVersion] | None = ...,
            quiet: Flag = ...,
            respect_ignore_files: Flag = ...,
            typeshed: Value = ...,
            verbose: Flag = ...,
            warn: Value = ...,
            watch: Flag = ...,
            **flags: Any,
        ) -> _R2:
            """Check a project for type errors

            Args:
                add_ignore: Adds `ty: ignore` comments to suppress all rule diagnostics.
                color: Control when colored output is used.
                config: A TOML `<KEY> = <VALUE>` pair (such as you might find in a `ty.toml` configuration file) overriding a specific configuration option.
                config_file: The path to a `ty.toml` file to use for configuration.
                error: Treat the given rule as having severity 'error'. May be repeated: a list emits the flag once per item.
                error_on_warning: Use exit code 1 if there are any warning-level diagnostics.
                exclude: Glob patterns for files to exclude from type checking.
                exclude_scripts: Exclude files containing PEP 723 inline script metadata unless passed explicitly. `exclude_scripts=off` emits `--include-scripts`. Added in 0.0.64.
                exit_zero: Always use exit code 0, even when there are error-level diagnostics.
                exit_zero_on_warning: Use exit code 0 if there are no error-level diagnostics.
                extra_search_path: Additional path to use as a module-resolution source (can be passed multiple times). May be repeated: a list emits the flag once per item.
                fix: Apply fixes to resolve errors.
                force_exclude: Enforce exclusions, even for paths passed to ty directly on the command-line. `force_exclude=off` emits `--no-force-exclude`.
                ignore: Disables the rule. May be repeated: a list emits the flag once per item.
                no_progress: Hide all progress outputs.
                output_format: The format to use for printing diagnostic messages.
                project: Run the command within the given project directory.
                python: Path to your project's Python environment or interpreter.
                python_platform: Target platform to assume when resolving types.
                python_version: Python version to assume when resolving types.
                quiet: Use quiet output (or `-qq` for silent output).
                respect_ignore_files: Respect file exclusions via `.gitignore` and other standard ignore files. `respect_ignore_files=off` emits `--no-respect-ignore-files`.
                typeshed: Custom directory to use for stdlib typeshed stubs.
                verbose: Use verbose output (or `-vv` and `-vvv` for more verbose output).
                warn: Treat the given rule as having severity 'warn'. May be repeated: a list emits the flag once per item.
                watch: Watch files for changes and recheck files related to the changed files.
            """
            ...
        @property
        def argv(self) -> Ty.Check[Argv]: ...

    check: Check[_R]
    def __call__(  # type: ignore[override]
        self,
        *args: str | PathLike[str],
        **flags: Any,
    ) -> _R:
        """An extremely fast Python type checker."""
        ...
    @property
    def argv(self) -> Ty[Argv]: ...
    def flags(
        self,
        **flags: Any,
    ) -> Self:
        """Bind tool-level global options before the subcommand.

        `tools.docker.flags(host=...)` puts a tool's own
        options ahead of the verb, where they belong."""
        ...
