"""Render a `ToolSpec` as the stub a type checker reads.

The bridge in `tools.py` translates keyword arguments mechanically and will
happily pass a flag no stub has heard of — that is what keeps it from going
stale. The stub is the other half: it tells an IDE what the installed tool
*currently* accepts, so the flags complete and their help text is right
there on hover, without importing the tool to find out.

Three things make a generated stub better than a hand-written one:

* it says what the tool says, because it was read from the tool;
* it can be regenerated, so a tool moving on is a diff rather than an
  archaeology exercise (`fm tools.audit` reports that diff);
* it can carry the tool's own prose per flag, including the one fact a
  bridge can never infer — how *this* tool spells "off".

Every generated verb still ends in `**flags: Any`, so a stub that lags the
installed tool degrades a hint and never a run.
"""

from __future__ import annotations

import re
import textwrap
from collections.abc import Iterable
from typing import cast

from footman._toolspec import Option, ToolSpec, Verb

_HEADER = """\
# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from {name} {version} on {platform}. In-process: {in_process}.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass. Each
# verb is a class parameterised by what its call returns, which is how
# `.argv` re-spells the same signature over `Argv` — same flags, same
# checking, a built command line instead of a run.
{imports}
"""


def render(
    spec: ToolSpec,
    *,
    platform: str = "",
    class_name: str = "",
    in_process: str = "",
) -> str:
    """The full text of `_stubs/<tool>.pyi` for *spec*."""
    root = class_name or _class_name(spec.name)
    body = _classes(_tree(spec.verbs), root)
    header = _HEADER.format(
        name=spec.name,
        version=spec.version or "an unpinned version",
        platform=platform or "this machine",
        in_process=in_process or ("available" if spec.in_process else "no"),
        imports=_imports(body),
    )
    return f"{header}\n{_typevars(body)}\n\n{body}"


def _imports(body: str) -> str:
    """Just the imports the body uses — an unused one fails the lint gate."""
    typing = ["Any"] + (["Literal"] if "Literal[" in body else [])
    if "-> Self:" in body:
        typing.append("Self")
    typing.append("TypeVar")
    aliases = ("_Flag", "_Value", "_ValuedFlag")
    # footman's own names are aliased private, because a subcommand becomes a
    # nested class named after the verb — and `uv tool` would otherwise
    # generate `class Tool(Tool)`, which cannot derive from itself. A verb
    # can never produce a leading underscore, so the collision is gone
    # rather than dodged.
    names = ["Argv as _Argv", "Tool as _Tool"] + [
        n for n in aliases if re.search(rf"\b{n}\b", body)
    ]
    lines = []
    if "Sequence[" in body:
        lines.append("from collections.abc import Sequence")
    lines.append(f"from typing import {', '.join(typing)}")
    lines.append("")
    lines.append(f"from footman.tools import {', '.join(names)}")
    return "\n".join(lines)


def _typevars(body: str) -> str:
    """One `TypeVar` per nesting depth the body reaches.

    Nested generic classes cannot rebind an enclosing class's TypeVar, so
    each depth gets its own (`_R`, `_R2`, `_R3`, …). Underscore-private on
    purpose: `ssh` really does have a flag named `R`, and a verb class can
    never lead with an underscore.
    """
    used = sorted(set(re.findall(r"\b_R\d*\b", body)))
    return "\n".join(f'{name} = TypeVar("{name}")' for name in used)


def _class_name(name: str) -> str:
    """`markdownlint-cli2` → `Markdownlint`. Public: these classes are the
    typed surface of `tools.<name>`, used (only in type position — they are
    stub-only, never imported at run time) as if they were public."""
    return "".join(part.title() for part in name.replace("-", "_").split("_"))


def _tree(verbs: Iterable[Verb]) -> dict[str, object]:
    """Nest dotted verb names: `compose.up` hangs under `compose`."""
    tree: dict[str, object] = {}
    for verb in verbs:
        node: dict[str, object] = tree
        parts = verb.name.split(".") if verb.name else []
        for part in parts[:-1]:
            child = node.setdefault(part, {})
            # cast: isinstance narrows to dict[Unknown, Unknown], which
            # invariant-dict checkers refuse to assign back; the tree is
            # str-keyed by construction.
            node = cast("dict[str, object]", child) if isinstance(child, dict) else {}
        node[parts[-1] if parts else ""] = verb
    return tree


def _tv(depth: int) -> str:
    """The TypeVar for classes at *depth* — a nested generic class cannot
    rebind its encloser's, so each depth carries its own."""
    return "_R" if depth == 0 else f"_R{depth + 1}"


def _classes(
    tree: dict[str, object], name: str, depth: int = 0, path: tuple[str, ...] = ()
) -> str:
    """One class, with every subcommand — group or verb — nested *inside* it.

    A subcommand belongs to its tool — `docker compose up` is not a
    `DockerCompose` that happens to sit beside `Docker`. Nesting says that
    in the only place it can be said, and the names stop being invented —
    `Docker.Compose.Up`, not `DockerComposeUp`, with no way for two tools
    to collide.

    Every class is generic over what its call returns: the module binding in
    `tools.pyi` fixes it to `Result`, and the `argv` property re-spells the
    same class over `Argv`. A leaf verb is just a tree whose only entry is a
    root verb, so one recursion renders tools, groups and verbs alike.
    """
    here = (*path, name)
    body: list[str] = []
    for key in sorted(tree):
        node = tree[key]
        if isinstance(node, dict):
            child = key.title().replace("_", "")
            subtree = cast("dict[str, object]", node)
            body.append(_indent(_classes(subtree, child, depth + 1, here)))
            body.append(f"    {key}: {child}[{_tv(depth)}]")
    for key in sorted(tree):
        node = tree[key]
        if isinstance(node, Verb) and key:
            child = key.title().replace("_", "")
            body.append(_indent(_classes({"": node}, child, depth + 1, here)))
            body.append(f"    {key}: {child}[{_tv(depth)}]")
    root = tree.get("")
    body.append(_method(root if isinstance(root, Verb) else None, depth))
    body.append(_argv_property(here, depth))
    # A tool with subcommands gets a typed `.flags()` returning `Self`, so a
    # globals-before-verb chain stays checked. The root verb's options are the
    # typed globals (git's `--git-dir`, docker's `--host`); a tool with none
    # still gets the override, for the chaining. `Self` rather than the class
    # by name: Self is what the chain means, and it keeps the parameterisation.
    # (footman run-control rides the inherited `.opts()`, typed on Tool.)
    if _has_subcommands(tree):
        globals_ = root.options if isinstance(root, Verb) else ()
        body.append(_flags_method(globals_))
    # Deriving from the *parameterised* base is what makes every member a
    # plain covariant override — `__call__` answers the inherited TypeVar
    # and `argv` narrows `Tool[Argv]` to a subclass of it — so no checker
    # needs a Liskov suppression.
    return f"class {name}(_Tool[{_tv(depth)}]):\n" + "\n".join(body)


def _argv_property(path: tuple[str, ...], depth: int) -> str:
    """The `argv` accessor: this class again, answering in `Argv`.

    The qualified name is spelled from module scope (`Docker.Compose.Up`)
    because a method annotation never sees the class scopes around it. A
    legal covariant override of the base property's `Tool[Argv]`, since
    every class here derives from `_Tool[…]`.
    """
    qualified = ".".join(path)
    line = f"    def argv(self) -> {qualified}[_Argv]: ..."
    if len(line) + 4 * depth <= 88:
        return f"    @property\n{line}"
    return (
        f"    @property\n    def argv(\n        self,\n    ) -> {qualified}[_Argv]: ..."
    )


def _indent(block: str) -> str:
    """A nested class body, one level in."""
    return "\n".join(
        f"    {line}" if line.strip() else line for line in block.split("\n")
    )


def _has_subcommands(tree: dict[str, object]) -> bool:
    """Whether this class has verbs to precede — the only case `.flags()`
    means anything (a global belongs *before* a subcommand)."""
    return any(key != "" for key in tree)


def _flags_method(options: tuple[Option, ...]) -> str:
    """The typed `flags()` for a tool's global options — returns `Self`, so
    `tools.docker.flags(host=…).compose.up(…)` stays checked. With no
    globals it is still declared, so the return type carries the chain.
    (footman run-control — nofail/capture/cwd/rel/… — goes on the
    inherited `.opts()`.)"""
    lines = ["    def flags(", "        self,"]
    typed = _unique(options)
    if typed:  # a `*` separator with only `**flags` after it is a syntax error
        lines.append("        *,")
        for option in typed:
            lines.append(f"        {_safe(option.name)}: {_annotation(option)} = ...,")
    lines.append("        **flags: Any,")
    lines.append("    ) -> Self:")
    lines.append('        """Bind tool-level global options before the subcommand.')
    lines.append("")
    lines.append("        `tools.docker.flags(host=...)` puts a tool's own")
    lines.append('        options ahead of the verb, where they belong."""')
    lines.append("        ...")
    return "\n".join(lines)


def _method(verb: Verb | None, depth: int = 0) -> str:
    """A class's `__call__` — the verb's own signature, answering in the
    class's TypeVar.

    footman run-control (nofail/capture/title/in_process/cwd/rel) lives on the inherited
    `.opts()`, never the call, so a call signature is pure flags — which also
    means an option literally named `capture` (pytest's) types through here.

    With no root verb to read (a bare group), the signature stays as wide as
    the inherited one — `*args: Any` — and adds only the return type, so
    nothing the runtime accepts becomes a type error.
    """
    header = "    def __call__(  # type: ignore[override]"
    if verb is None:
        return "\n".join(
            [
                header,
                "        self,",
                "        *args: Any,",
                "        **flags: Any,",
                f"    ) -> {_tv(depth)}: ...",
            ]
        )
    positional = _positional_lines(verb)
    options = _unique(verb.options)
    # A bare `*,` must be followed by a keyword-only parameter; when the only
    # thing after it would be `**flags`, drop it — `def f(self, **flags)` already
    # forbids a positional. (Previously the nofail/in_process params backfilled
    # the `*,`; those moved to `.opts()`.)
    if positional == ["        *,"] and not options:
        positional = []
    lines = [header, "        self,", *positional]
    for option in options:
        lines.append(f"        {_safe(option.name)}: {_annotation(option)} = ...,")
    lines.append("        **flags: Any,")
    lines.append(f"    ) -> {_tv(depth)}:")
    doc = _docstring(verb, depth)
    if doc:
        lines.append(doc)
    lines.append("        ...")
    return "\n".join(lines)


def _positional_lines(verb: Verb) -> list[str]:
    """The positional part of a verb's signature, from its usage shape.

    `"none"` → keyword-only (`*,`), so a stray positional is a type error;
    `"required"` → a positional-only leading argument, so passing it by
    keyword is one too; `"any"` → `*args`, the conservative default that
    forbids nothing.
    """
    if verb.positional == "none":
        return ["        *,"]
    if verb.positional == "required":
        lead = _safe(verb.lead) if verb.lead else "arg"
        # If the leading positional's name also names an option, the two
        # would collide into one parameter. Can't spell both, so don't
        # constrain: fall back to `*args`.
        if lead in {_safe(o.name) for o in verb.options}:
            return ["        *args: str,"]
        return [f"        {lead}: str,", "        /,", "        *args: str,"]
    return ["        *args: str,"]


# The method's own structural parameters. An option named the same (git
# rev-parse has `--flags`) would be a duplicate parameter — it still works,
# swallowed by `**flags` at type-check and `**kwargs` at run time, just not
# typed. `nofail`/`in_process` are no longer here — they moved to `.opts()`, so
# a tool that really has a `--nofail` flag now types through the call.
_RESERVED = frozenset({"self", "args", "flags"})


def _unique(options: tuple[Option, ...]) -> list[Option]:
    """One parameter per keyword — a repeat would be a syntax error, and a
    name that clashes with a fixed parameter is dropped to the catch-all."""
    seen: dict[str, Option] = {}
    for option in options:
        safe = _safe(option.name)
        if safe not in _RESERVED:
            seen.setdefault(safe, option)
    return list(seen.values())


def _listed(names: tuple[str, ...]) -> str:
    """`Windows`, `macOS and Windows`, `Linux, macOS and Windows`."""
    if len(names) == 1:
        return names[0]
    return f"{', '.join(names[:-1])} and {names[-1]}"


def _safe(name: str) -> str:
    """A flag whose name is a Python keyword takes footman's trailing `_`."""
    import keyword

    return f"{name}_" if keyword.iskeyword(name) else name


def _esc(text: str) -> str:
    r"""Double every backslash: a help string like mypy's `--exclude '\.py$'`
    must land as a literal in the generated docstring, not an invalid `\.`
    escape sequence that a compiler warns on."""
    return text.replace("\\", "\\\\")


def _annotation(option: Option) -> str:
    """The stub's declared type for one option.

    Deliberately wide, because the stub's contract is to suggest and never
    to forbid. `_Value` takes a sequence as well as a scalar for *every*
    option, since the bridge repeats a flag for each item and whether the
    tool accepts repetition is the tool's business, not the stub's —
    `select=["E", "F"]` works, so it must type-check.

    A closed set of values is the one place a narrow type earns itself: a
    `Literal` makes the IDE offer the values, and the tool would reject a
    non-member anyway.
    """
    if option.type_name == "bool":
        return "_Flag"
    if option.type_name == "optvalue":
        return "_ValuedFlag"  # usable bare or with a value — `--gpg-sign[=<key>]`
    if option.choices:
        literal = "Literal[" + ", ".join(repr(c) for c in option.choices) + "]"
        return f"{literal} | Sequence[{literal}] | None"
    return "_Value"


def _docstring(verb: Verb, depth: int = 0) -> str:
    """The verb's own help, plus one `Args:` entry per flag.

    Google-style because two readers want it: Pylance surfaces a
    parameter's line on hover and in the completion popup, and griffe reads
    the same section to build the reference page — so the tool's help text
    is written once and lands in both.
    """
    documented = [o for o in _unique(verb.options) if o.help or o.negation]
    if not verb.help and not documented:
        return ""
    summary = textwrap.wrap(
        _esc(verb.help) or "Run this verb.",
        width=84 - 4 * depth,
        initial_indent=" " * 8,
        subsequent_indent=" " * 8,
        break_long_words=False,
        break_on_hyphens=False,
    ) or [" " * 8 + "Run this verb."]
    summary = _md_safe(summary)
    summary[0] = '        """' + summary[0].lstrip()
    lines = list(summary)
    if documented:
        lines.append("")
        lines.append("        Args:")
        for option in documented:
            lines.extend(_arg_lines(option, depth))
    lines.append('        """')
    return "\n".join(lines)


# A wrapped docstring line whose first non-space character opens a Markdown
# block renders as that block in the reference page (griffe reads these).
# Python-Markdown is lenient: `#2` (git's merge-stage notation) is a header
# and `>x` a blockquote, no space required. Both escape as `\#` / `\>`.
_LEADING_MD = re.compile(r"^(#|>)")


def _md_safe(lines: list[str]) -> list[str]:
    """Escape a Markdown block marker a wrap left at a line's start.

    The backslash is doubled: this text becomes a docstring in the
    generated `.pyi`, where a lone `\\#` would be an invalid escape
    sequence — `\\\\#` is the literal `\\#` that Markdown renders as `#`.
    """
    out: list[str] = []
    for line in lines:
        indent = line[: len(line) - len(line.lstrip())]
        content = line[len(indent) :]
        out.append(f"{indent}\\\\{content}" if _LEADING_MD.match(content) else line)
    return out


def _arg_lines(option: Option, depth: int = 0) -> list[str]:
    """One `Args:` entry, wrapped, with the `off` spelling when it matters."""
    text = _esc(option.help).rstrip(".")
    if option.type_name.startswith("list[") or option.type_name.endswith("[]"):
        text = f"{text}. May be repeated: a list emits the flag once per item"
    if option.type_name == "optvalue":
        text = f"{text}. Value optional: `True` for the bare flag, or pass one"
    if option.negation:
        default_on = option.default is True
        lead = "Defaults on — " if default_on else ""
        text = f"{text}. {lead}`{option.name}=off` emits `{option.negation}`"
    elif option.default not in (None, "", False):
        text = f"{text}. Defaults to `{option.default}`"
    # What the history knows, and only what it knows: an option already
    # present at the oldest release read carries no `since`, because the
    # chain never looked far enough back to claim one. A removed option is
    # still rendered — the reader may be on a version that has it — and this
    # is the line that says otherwise.
    if option.until:
        text = f"{text}. Gone since {option.until}"
    elif option.since:
        text = f"{text}. Added in {option.since}"
    # Said only where a platform looked and did not find it: nothing here
    # means nothing contradicts the option, which is the common case and the
    # reason the store keeps only the exceptions.
    if option.not_on:
        text = f"{text}. Not available on {_listed(option.not_on)}"
    wrapped = textwrap.wrap(
        f"{_safe(option.name)}: {text}.".replace("  ", " "),
        width=84 - 4 * depth,
        initial_indent=" " * 12,
        subsequent_indent=" " * 16,
        break_long_words=False,
        break_on_hyphens=False,
    )
    return _md_safe(wrapped) or [f"{' ' * 12}{_safe(option.name)}: ."]
